### ISSUE TITLE
Is ArrayBased queue a circular queue?

### ISSUE THREAD

**Issue by vaibhav26sharma** [ani03sha/Algorithms#50]
@ani03sha  Can you please confirm if Array based queue implementation is a circular queue[https://github.com/ani03sha/Algorithms/blob/5955c2f42b9f38f3e842bbab1d25004f238fd06d/src/main/java/org/redquark/algorithms/datastructures/queues/ArrayBasedQueue.java#L68](url) ?

It looks to be, considering you are setting rear = 0 while insertion but I think that condition is not right and should be modified as below:
**Old:**
`if (rear == capacity) {
            // Rotate the rear of the queue
            rear = 0;
        }`

**New**
`if (rear == capacity && front != 0) {
            // Rotate the rear of the queue
            rear = 0;
        }`

**Comment by ani03sha** [comment]
@vaibhav6451956, ~~no, it's not a circular queue.~~ yes, you are right. The reason being is that if `front` was 0 and `rear` was capacity - 1, then we would have hit the special condition - 
```java
if (size == capacity) {
    throw new IndexOutOfBoundsException("Queue is full. Cannot add!");
}
```
Since we are past that, it means `front` is anywhere between 0 and capacity - 1.

LMK if you have further questions on that. Cheers!

**Comment by vaibhav26sharma** [comment]
@ani03sha  Thanks for the explanation, but what do you intend to do by resetting `rear=0` ?

**Comment by ani03sha** [comment]
> @ani03sha Thanks for the explanation, but what do you intend to do by resetting `rear=0` ?

It means we have space left and the last index of our inner array is filled, therefore, we are moving the rear to the index zero.
Let's say if the size of the array is 10 and we have 5 elements where `front` is at the index 5, then our array would look like -

```
X  X  X  X  X  E  E  E  E  E
```

where *X* represents empty and *E* represents an element. Now, if we add a sixth element, our inner array would look like - 

```
E  X  X  X  X  E  E  E  E  E
```

**Comment by vaibhav26sharma** [comment]
@ani03sha Thanks for that elaborated explanation, but what you have just explained is a circular queue, ain't it? Since you are moving the rear back to 0 if the slots in the front are empty due to dequeue() operations, there has to be a link/connection between the rear and front which is the case in a circular queue only. That's what got me confused.

AFAIK, this happens in a circular queue only, was it a linear queue we wouldn't have been looking for slots in the front part of the array and that's the disadvantage of a linear array-based queue also, where slots get wasted.

**Comment by ani03sha** [comment]
Yes, you are right! I just checked the exact definition of Circular Queue [here](https://towardsdatascience.com/circular-queue-or-ring-buffer-92c7b0193326) and what you are saying is correct. Thanks for pointing it out.
